

tickers <- c("RA.MX", "OMAB.MX", "ALSEA.MX", "BBAJIOO.MX", "VESTA.MX", "KOFUBL.MX", "CHDRAUIB.MX",
             "ASURB.MX", "CUERVO.MX", "GRUMAB.MX", "GCC.MX", "BIMBOA.MX", "AC.MX", "TLEVISACPO.MX",
             "LABB.MX", "GMEXICOB.MX", "PINFRA.MX", "GAPB.MX", "KIMBERA.MX", "CEMEXCPO.MX", "AMXB.MX",
             "Q.MX", "BOLSAA.MX", "GCARSOA1.MX", "GFNORTEO.MX", "MEGACPO.MX", "ORBIA.MX", "GENTERA.MX")
